spring: 
  application: 
    name: eurekaServer
  autoconfigure.exclude: org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration
server: 
  port: 8081
#  servlet: 
#    context-path: /eureka/v1.0/
  
eureka:
  server:
    enableSelfPreservation: false
    #eviction-interval-timer-in-ms: 1000
  instance:
    hostname: localhost
    #preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: 
        http://${eureka.instance.hostname}:${server.port}/eureka/